### ISSUE TITLE
Canonical disappears on PS 1.5.6 

### ISSUE THREAD

**Issue by ZiZuu-store** [ZiZuu-store/zzSEOtk#14]
Reported by **tictacarea** https://www.prestashop.com/forums/topic/328680-hreflang-and-canonical-links-creation-on-prestashop-16/?p=2128921

It should be related to the PS version .. needs feedback to be debugged

"*On index page I can see in any language if the canonical option is not selected in backoffice (in your module) if I select it, then it disapears at all.*"

**Comment by adversor** [comment]
Hi ZiZuu,

I have the same problem, but with the newest version PS 1.6.1.1.

If canonical meta tags are enabled, the hreflang-links disappear on index page. With 'canonical meta tags' switched to no, hreflang-links are there as it should be.

Thanks for your sharing your great module!

**Comment by ZiZuu-store** [comment]
Thank you for your feedback.  Going to investigate .. hope in a fix shortly

**Comment by ZiZuu-store** [comment]
@adversor can you please try the **[fix_issue_14 branch](https://github.com/ZiZuu-store/zzSEOtk/tree/fix_issue_14)** ?

I think it should fix all the issue in a step .. please confirm if true

**Comment by adversor** [comment]
still no hreflang links on index page when canonical is enabled...

**Comment by ZiZuu-store** [comment]
Can you provide any kind of access to your test server? It will be useful to be able to debug

**Comment by adversor** [comment]
will setup an online installation tonight, actually only local. off-line for some hours now.

**Comment by ZiZuu-store** [comment]
:+1:  thank you so much :)

**Comment by ZiZuu-store** [comment]
I argue [zzseotk.php on #L261](/ZiZuu-Store/zzSEOtk/tree/dev/zzseotk.php#L261) fails to calculate the $requestedURL for index...

**Comment by ZiZuu-store** [comment]
@adversor I made a patch that should change something .. if you can test it, possibly on a older PS version too I'll be grateful :)

Thank you for your time

**Comment by adversor** [comment]
Showing hreflang links for www.example.com/en and www.example.com/de now, but not when typing www.example.com directly into the browser. Using default .htaccess. I am actually not sure what's the best behaviour in terms of SEO for the different index pages.

**Comment by ZiZuu-store** [comment]
So your default lang is en, but you have two different en version for the
HP (or for the entire site?) ...

Site.com/ and site.com/en/ are both browseable ? no redirect 301 from one
to other?

If so only one of the available "clones" should be available to SE, being
the canonical one.
Hreflags have to be only on the canonical pages ...

Please verify your case ...



Il martedì 1 settembre 2015, adversor <notifications@github.com> ha scritto:

> Showing hreflang links for www.example.com/en and www.example.com/de now,
> but not when typing www.example.com directly into the browser. Using
> default .htaccess. I am actually not sure what's the best behaviour in
> terms of SEO for the different index pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/zzSEOtk/issues/14#issuecomment-136846108>.
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by adversor** [comment]
can u come to gitter?
