### ISSUE TITLE
No hreflang links on supplier and manufacturer listing page

### ISSUE THREAD

**Issue by adversor** [ZiZuu-store/zzSEOtk#18]
Using PS 1.6.1.1 and zzSEOtk 1.1.4

I have no hreflang links on manufacturer and supplier listing pages, SEO friendly URL enabled: 
www.example.com/en/manufacturers
www.example.com/en/supplier

adversor.

**Comment by ZiZuu-store** [comment]
Hi @adversor,
  some more infos:
- enabling or not "**canonical**" makes some difference?
- PS clean urls are enabled?
- do you have any third party module acting on URLs (remove IDs or similar) enabled or installed?
- **en** is your default language?

Thank you for your time

**Comment by ZiZuu-store** [comment]
fix_issue_14 branch should fix

**Comment by adversor** [comment]
Thanks for taking care.
I just have set up a clean new PS 1.6.1.1. site locally with default theme an no additional modules installed.  I have added fix_issue_14 branch. EN is default language, DE is second.

With Friendly URL switched on in PS, I get a wrong canonical link and no hreflang links. On 
http://localhost/ps1611/en/manufacturers it looks like this:
```<link rel="canonical" href="http://localhost/ps1611/en/_" />```

I  am not sure if it make sense, but with friendly URLs switched off in PS for example to
http://localhost/ps1611/index.php?id_product=2&controller=product&id_lang=1

hreflang and canonical links always point to index page, independent which page.

```<link rel="alternate" hreflang="x-default" href="http://localhost/ps1611/index.php" />```
```<link rel="alternate" hreflang="en-us" href="http://localhost/ps1611/index.php" />```
```<link rel="alternate" hreflang="de-de" href="http://localhost/ps1611/index.php" />```
```<link rel="canonical" href="http://localhost/ps1611/index.php" />```

**Comment by ZiZuu-store** [comment]
Does **fix_home_canonical_hreflang** branch fix it now?

**Comment by ZiZuu-store** [comment]
going to debug thanks to your VPS (Thank you very much).

At a first look the problem is that $context->link  seems to be empty on manufatures/suppliers page .. going to investigate deeper, stay tuned ;)

**Comment by ZiZuu-store** [comment]
@adversor thank you again for your great help. Bug fixed AFASCS

Going to release.

**Comment by adversor** [comment]
great work. fixed also on my real site now. Thanks!

**Comment by ZiZuu-store** [comment]
:+1:  you can remove my account on your test server of course 

Thank you again
