### ISSUE TITLE
Wrong hreflinks on manufacturer/supplier page

### ISSUE THREAD

**Issue by adversor** [ZiZuu-store/zzSEOtk#19]
Using PS 1.6.1.1 and zzSEOtk 1.1.4

On a dedicate manufacturer page, I get wrong hreflinks, all pointing to active language only. e.g.:

```<link rel="alternate" hreflang="x-default" href="http://localhost/ps161/en/1_fashion-manufacturer" />```
```<link rel="alternate" hreflang="en-us" href="http://localhost/ps161/en/1_fashion-manufacturer" />```
```<link rel="alternate" hreflang="de-de" href="http://localhost/ps161/en/1_fashion-manufacturer" />```
```<link rel="canonical" href="http://localhost/ps161/en/1_fashion-manufacturer" />```

Same problem on a dedicated supplier page. 

Sorry for many issues, maybe I have some misconfiguration. But I have tested it on my actual local project and on a default new PS installation just set up. I'm using xampp / php 5.5.19 on a local windows machine.

adversor.

**Comment by ZiZuu-store** [comment]
Hi,
  thank you for reporting.

You have no misconfiguration I guess .. simply all your issues are about "features" I did not test directly because we don't use them on our shop .. so please apology and help us debug and fix them :)

Thanks

**Comment by ZiZuu-store** [comment]
fix_issue_14 should fix it .. please confirm

**Comment by adversor** [comment]
with fix_issue_14 this problem is solved! When friendly URLs switched on, from 
http://localhost/ps1611/en/1_fashion-manufacturer it looks like it should be:

```<link rel="alternate" hreflang="x-default" href="http://localhost/ps1611/en/1_fashion-manufacturer" />```
```<link rel="alternate" hreflang="en-us" href="http://localhost/ps1611/en/1_fashion-manufacturer" />```
```<link rel="alternate" hreflang="de-de" href="http://localhost/ps1611/de/1_fashion-manufacturer" />```
```<link rel="canonical" href="http://localhost/ps1611/en/1_fashion-manufacturer" />```

**Comment by ZiZuu-store** [comment]
great :)  now will fight against remaining issues :) .. can you join the gitter chat?
