### ISSUE TITLE
rel="canonical" and JS pagination (using "#")

### ISSUE THREAD

**Issue by guil182** [ZiZuu-store/zzSEOtk#27]
in a category page.
whatever the page, the canonical tag is always "http: // website / category /" when it should be "http: // website / category / # / Page-2" on page 2, etc. etc.

**Comment by ZiZuu-store** [comment]
absolutely not :)

it should be http: // website / category / ?p=2 ..

**Comment by guil182** [comment]
ok, but it is always "http: // website / category /" :(

**Comment by ZiZuu-store** [comment]
If your theme is handling pagination as a "show all" category page **and** a JS pagination (using hashes "**#**") then the right canonical is to have the same page for every "fake pagination" ...

You should disable JS and see the "real" beaviour

**Comment by guil182** [comment]
i have the warehouse theme and you are true, it's a js pagination.
but how to disable it ? :(

**Comment by ZiZuu-store** [comment]
You don't have to disable it .. it is acting right as far as I can see ...


See at https://zizuu.com .. we have the same pagination . .and I can assure google is appreciating

**Comment by guil182** [comment]
but a disable "show all" because on a category with 500 products, it's two slow....it's an error ?

**Comment by guil182** [comment]
so, for you, on my page http://www.millesime-online.com/fr/bordeaux/ everything is ok ?

**Comment by ZiZuu-store** [comment]
From a SEO point of view yes ... no problems as the JS pagination has the "rel=nofollow" set and there is a form for non JS/ search engines pointing to the "show all" page ..

As you pointed out you have ~ 500 items, and you can have performances issue .. but it is another problem ..

![screen shot 2015-09-15 at 09 17 26](https://cloud.githubusercontent.com/assets/6018431/9870291/f3dda3ae-5b8a-11e5-809e-1356aa5a4b67.png)
 
Can I close this issue?

**Comment by guil182** [comment]
yes, thank you

**Comment by ZiZuu-store** [comment]
As zzSEOtk correctly handles pagination (just try appending **?p=4** and check the canonical) you could modify your pagination.tpl:
- remove the form
- add a "<link rel=prev/next" just above the current "#"-link using the non-hashed URL (category/?p=4 )

this way search engine will see every page and performance issues will go out. canonical will work with no work to perform

**Comment by guil182** [comment]
when i add ?p=4 canonical is : 
<link href="http://www.millesime-online.com/fr/bordeaux/?p=4" rel="canonical">

but how to do this ?
- remove the form
- don't touch current pagination link
- add a "<link rel=prev/next" just above the current "#"-link using the non-hashed URL (category/?p=4 )

**Comment by ZiZuu-store** [comment]
This was a suggestion to hack your theme .. in case you have the necessary technical skill

 .. sorry but this is not related to the modules AFAICS ..
