### ISSUE TITLE
Wrong Canonical protocol for categories on HTTPS

### ISSUE THREAD

**Issue by WebmonsterNL** [ZiZuu-store/zzSEOtk#32]
I'm having difficulties with the canonical tag.

It doens't seem to work with SSL. The module uses the http url instead of the https version.

**Comment by ZiZuu-store** [comment]
The module uses core PS functions for this task .. can you please tell me what PS version are you using?

**Comment by WebmonsterNL** [comment]
Hi ZiZuu,

I'm using 1.6.0.14. I've activated SSL for all pages.

Hope this helps!

**Comment by ZiZuu-store** [comment]
Thanks, will investigate ASAP (sorry I'm very busy these days)

**Comment by ZiZuu-store** [comment]
I think it is due to this bug fix we made on PS Prestashop/Prestashop#2888

PS < 1.6.1.0 have this bug .. so you should upgrade PS or wait we will support older version of PS some way

**Comment by ZiZuu-store** [comment]
@WebmonsterNL 
- is the canonical tag wrong on every page or only for CMS | product | category pages?
- Can you provide me a live example?

**Comment by WebmonsterNL** [comment]
Hi ZiZuu,

I've activated it temporarily on our live site:

https://www.cvkoopjes.nl/shop/

It seems to be not working on the category pages only.

Please let me know when you're done with the live example so I can turn it off again (I don't want any problems with Google obviously)

Thanks!

**Comment by ZiZuu-store** [comment]
OK you can disable now, got the info

Will investigate.  Thanks

**Comment by ZiZuu-store** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uQdJ5PRL&#x2F;11-wrong-canonical-protocol-for-categories-on-https"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Wrong Canonical protocol for categories on HTTPS</a>

**Comment by ZiZuu-store** [comment]
@WebmonsterNL can you confirm you still have this isuue on last version?

Do you still have PS 1.6.0.14 ?

**Comment by WebmonsterNL** [comment]
Hi ZiZuu,

Due to the urgenty of our live site we had to buy a payed module to get the canonicals working correcty. I'm not in a position anymore to switch that for your module so unfortunately I can't test it for you.

**Comment by ZiZuu-store** [comment]
OK no problem, thanks

As it works in current PS versions and because recent PS versions fixed a number of https-related issues I'm going to close this one.

If anybody needs to reopen feel free to do
