### ISSUE TITLE
500 server error with hreflang module

### ISSUE THREAD

**Issue by studio1one** [ZiZuu-store/zzSEOtk#37]
I installed your module but it seems like Google found many errors after I install it, module make 404 to 500 server error and Im not sure if there are more conflicts in our store because of this.

![skarmavbild 2015-12-02 kl 17 40 07](https://cloud.githubusercontent.com/assets/16121283/11537095/c7b5f492-991b-11e5-9587-1a1061385c25.jpg)

**Comment by ZiZuu-store** [comment]
Hi @studio1one 
  the errors in the pic are **not** server error (nor 500 neither other codes) .. they are some hreflang related issues.

It looks like some of your pages have no counterparts association between hreflang=XX and x-default


If you click on the error row you should see what pages are rising the issue .. as you just configured hferlang it is possible that those errors are spurious and could decrease in the time untile being removed at all .. google can take months to reindex all your site ..


As the last days in your pic are showing a downgrade in the errors I think the above scenario can be the right one ..


Please monitor your stats and let me know if the are going away at all

**Comment by studio1one** [comment]
I have uninstalled it since that happen.

**Comment by studio1one** [comment]
oooh sorry, it was two, that image was one issue that show 124  Hreflang-tags with error.
I hade 20 errors in webmaster tools with 500 error code, and I checked with redirect checker and it show 500 code, but when I uninstalled it , then it was okey again.

**Comment by ZiZuu-store** [comment]
Uhmmmm sorry but I can't understand what exactly happened.

- PS version?
- zzseotk version?
- how many shops/languages 
- Any way to reproduce?

Thanks

**Comment by studio1one** [comment]
PS version: 1.6.1.0
zzseotk version: 1.0.0
1 shop www.corecosmetic.com 5 languages
To reproduce it I can use my CLONE of the store if that can help?

**Comment by ZiZuu-store** [comment]
It would be great :)

I'll work on the issue if will have a way to reproduce and debug

You can join the chat to discuss and collaborate easier 

Thank you very much

**Comment by ZiZuu-store** [comment]
@studio1one r u still there?
