### ISSUE TITLE
Multishop https/http issue

### ISSUE THREAD

**Issue by hannes01** [ZiZuu-store/zzSEOtk#44]
Hi,

thanks for the great module! I'm not an expert on this field but I think there's an issue on my site. 
I use Presta's multishop feature and in Shop2 uses SSL. There's no SSL in Shop1. As a result Shop1 URL's start with "http" and Shop2 URL's start with "https".

However when using Zizuu module, I get this result:

![hreflang](https://cloud.githubusercontent.com/assets/17709332/13579254/1a5a6078-e4a5-11e5-9082-1051db6f115e.jpg)

This does not seem right. I think something probably needs to be changed in /modules/zzseotk/views/templates/hook/meta-hreflang.tpl file? Unfortunately this is beyond my expertise as I'm not the coder.

Thanks for help!

Best regards,
Hannes

PS. What is the right action in Presta multishop - currently its possible to enable the module in 3 different shop modes: Shop1/ Shop2/ All Shops. Should it be enabled in all 3 modes?

**Comment by ZiZuu-store** [comment]
Hi,
 Thanks for your report.

I think you could have cough a case not correctly handled.

Unfortunately we have not a large number of use cases in  working multi-shop environments .. afaics you should enable it on all shops

We will investigate as soon as possible

Thank you

**Comment by hannes01** [comment]
Thanks! Please let me know if you need my server details.

Best regards,
Hannes

**Comment by ZiZuu-store** [comment]
Of course any info you can provide is appreciated.

If you could give me access to a testing server to reproduce and debug it would be great too

**Comment by hannes01** [comment]
Hi,

unfortunately I don't have the testing server in multishop mode. But I can send you the details of the live one. Shall I send it to info@ZiZuu.com ?

Thanks,
Hannes

**Comment by ZiZuu-store** [comment]
Yes, thank you very much

**Comment by hannes01** [comment]
Done!

Thanks.

**Comment by ZiZuu-store** [comment]
I'm investigating .. first of all: why the main URL for both shops is http:// ? the .eu shop should be https:// .. or not?

![screen shot 2016-03-12 at 15 50 04](https://cloud.githubusercontent.com/assets/6018431/13723603/520ae786-e86a-11e5-843f-58ca98898a15.png)

**Comment by hannes01** [comment]
You are absolutely correct! I installed SSl  a week ago and totally forgot about this part of the BO.

Feel free to change it! Maybe this will solve the issue...

BR,
Hannes

**Comment by ZiZuu-store** [comment]
Deep reading PS help I think it as to be leaved as it is ... SSL domain is the domain part, without schema .. still reading for a confirmation.

Another point is that it seems that meta tags are added only on the main shop .. and this is wrong too ..

**Comment by hannes01** [comment]
Thanks for info. 

Exactly which meta tags do you have in mind?

**Comment by ZiZuu-store** [comment]
Sorry, I mean the meta tags added by my module .. in the secondary shop they are not present AFAICS

I found another strange behavior: "[www.e-pood.kalaportaal.ee/spinnigurullid/341-daiwa-freams-rull.html](www.e-pood.kalaportaal.ee/spinnigurullid/341-daiwa-freams-rull.html)" should redirect to the non-www version .. but it returns a 404 error

**Comment by hannes01** [comment]
Hmmm... did not know that, thanks for looking into it.

**Comment by ZiZuu-store** [comment]
It seems the shop is well configured .. I have to look into the code and debug it. 

But this is a production shop, so I'll give a quick look into the code but will not touch anything. I'll have to setup a testing environment on my server with the same configuration to reproduce to problem and then debug and fix 

Will need still some days ..

**Comment by hannes01** [comment]
OK, I understand. Thanks!

**Comment by hannes01** [comment]
Hi there,

have you had any luck yet?

Thanks,
Hannes

**Comment by ZiZuu-store** [comment]
Hi @hannes01 .. sorry but I had a very busy week .. no news

**Comment by hannes01** [comment]
Hi,

thanks for info buddy. As I'm planning to hire SEO team ASAP (main fishing season is starting very-very soon), it would be great to have this issue solved before that.

Maybe it would fasten the progress, if you still work on production shop, but we properly back up everything?

Thanks,
Hannes

**Comment by ZiZuu-store** [comment]
Sorry, but we develop this module mainly for our shop, then release it for the community .. we can't assure short release times as our main job is not maintaining this module.

I'm doing my best to find the time to address this issue, but I can't give you a milestone .. I'm very sorry

I'm configuring a test server right now, hope to have a solution in the next days .. but I'm afraid the problem could be in a PS core bug .. have to investigate deeper ..

**Comment by ZiZuu-store** [comment]
I'm looking to your site .. in order to clone it on my devel server ... I noticed a number of "strange" things I think you should fix .. 

For example, you have a `__MACOSX` dir in /modules .. it was proven to create problems on my tests .. you should remove it


Please join the chat at https://gitter.im/ZiZuu-store/zzSEOtk in order to better interact. Thanks
