### ISSUE TITLE
Verison 1.2.2

### ISSUE THREAD

**Issue by hannes01** [ZiZuu-store/zzSEOtk#48]
Hey,

thanks for the new version. However after installing it by site turned blank. Right now i disabled the module and the site is up again.

What could be wrong?

If you need to check the server, the access details are the old ones.

Thanks!

Hannes

**Comment by ZiZuu-store** [comment]
I Think it was my bad .. I erroneously committed broken code. Sorry for that

Will release a fixed version early

**Comment by hannes01** [comment]
Hi,

no worries, thanks for info!

BR,
Hannes

**Comment by ZiZuu-store** [comment]
Fixed, already updated on your shop

thank you for your support

**Comment by hannes01** [comment]
Hi,

please find the Estonian translation of SEO module, as promised. Sorry for the delay! :)

[et.zip](https://github.com/ZiZuu-store/zzSEOtk/files/383855/et.zip)

Best regards,
Hannes

**Comment by ZiZuu-store** [comment]
thank you very much :)
