### ISSUE TITLE
Error on Prestashop 1.6.1.6 / PHP 5.2.17

### ISSUE THREAD

**Issue by santinuro** [ZiZuu-store/zzSEOtk#52]
Hi,
I have installed the module in my prestahop 1.6.1 and I get this error

[PrestaShop] Fatal error in module file :/home2/pnrandei/public_html/www.bromontbiking.com/modules/zzseotk/zzseotk.php:
syntax error, unexpected T_STRING

**Comment by ZiZuu-store** [comment]
Hi

Could you please give your PS exact version, your PHP version and the version of the module you are installing?

Moreover, try to uninstall, clean all caches, then install again

Thanks for reporting

**Comment by ZiZuu-store** [comment]
@santinuro ..

**Comment by santinuro** [comment]
Hi, 
PS version 1.6.1.6
Module version 1.2.3
PHP version, I don´t know.. how can I know that?

Thank you very much!!

**Comment by ZiZuu-store** [comment]
@santinuro 

- Did you uploaded the following ZIP? www.bromontbiking.com/modules/zzseotk/zzseotk.php

- To see PHP version go in Admin > Advanced Parameters > Informations or create a `_info.php` file containing `<?php phpinfo();`

- Can you give me the entire error you got? With line numbers too

**Comment by santinuro** [comment]
Hi,

- Did you uploaded the following ZIP? www.bromontbiking.com/modules/zzseotk/zzseotk.php

Yes, but I have deleted it

-To see PHP version go in Admin > Advanced Parameters > Informations or create a _info.php file containing <?php phpinfo();
This is what I can see:

 Información del servidor Linux #1 SMP Tue Jan 22 16:19:19 EST 2013 x86_64

Versión del servidor web Apache

Versión de PHP 5.2.17

Límite de memoria 128M

Tiempo Máximo de ejecución 30 

-Can you give me the entire error you got? With line numbers too
Uhmm I don´t know how to do that. When I go to www.bromontbiking.com after installing the pluging the screen shows

"[PrestaShop] Fatal error in module file :/home2/pnrandei/public_html/www.bromontbiking.com/modules/zzseotk/zzseotk.php:
syntax error, unexpected T_STRING"

**Comment by ZiZuu-store** [comment]
Uhmmm .. I think your PHP version is not supported .. I'd need to know the line of your error in order to try to rewrite the code in a way working with your PHP ...   can you look at your server logs???

**Comment by ZiZuu-store** [comment]
OK found the problem .. I'm going to fix it ..

**Comment by santinuro** [comment]
OK!!!

**Comment by ZiZuu-store** [comment]
Fixed in **release 1.3.0** :)
